### ISSUE TITLE
Incompatible with shine.lua

### ISSUE THREAD

**Issue by JanWerder** [rxi/autobatch#1]
When the shine boxblur shader is active, autobatch crashes the game.

![image](https://cloud.githubusercontent.com/assets/596986/16902085/6b84a3ac-4c54-11e6-94ce-c1193b21a857.png)
![image](https://cloud.githubusercontent.com/assets/596986/16902086/6e14276e-4c54-11e6-9bfd-80cf27c3e550.png)
![image](https://cloud.githubusercontent.com/assets/596986/16902087/6f60db62-4c54-11e6-97fc-e304a358f55b.png)

**Comment by rxi** [comment]
The commit should fix this issue -- let me know if this isn't the case, though! Thanks.

**Comment by JanWerder** [comment]
Fixed the issue -- thanks
