### ISSUE TITLE
2 Bugs Related to setColor()

### ISSUE THREAD

**Issue by oniietzschan** [rxi/autobatch#2]
I've created a small main.lua which demonstrates a couple of ways that the behaviour of this library deviates from the expected result in Love 0.10.2.

```lua
-- main.lua

local origLoveGraphics = love.graphics
require 'autobatch'

local catImage = love.graphics.newImage('demo/cats/cat.png')

function _helpDraw(label, lg, x)
  local startingDrawCalls = lg.getStats().drawcalls
  lg.print(label, x, 30)

  -- Demonstrate BUG 1: love.graphics.push('all') .pop()
  lg.setColor(255, 128, 128)
  lg.push('all')
  lg.setColor(128, 255, 128)
  lg.push('all')
  lg.setColor(128, 128, 255)
  lg.draw(catImage, x, 115) -- Should be BLUE
  lg.pop()
  lg.draw(catImage, x, 170) -- Should be GREEN
  lg.pop()
  lg.draw(catImage, x, 225) -- Should be RED

  -- Demonstrate BUG 2: love.graphics.setColor() values over 255
  local val = 255 * 1.5
  lg.setColor(val, val, val)
  lg.draw(catImage, x, 330) -- Should be BRIGHT
  val = 255 * 2
  lg.setColor(val, val, val)
  lg.draw(catImage, x, 385) -- Should be RIGHTER
  val = 255 * 2.5
  lg.setColor(val, val, val)
  lg.draw(catImage, x, 440) -- Should be BRIGHTEST

  -- Print all text.
  -- Note that we do this at the end so that drawcalls aren't affected by lg.print()
  lg.setColor(0, 0, 0)
  local drawCalls = lg.getStats().drawcalls - startingDrawCalls
  lg.print("drawcalls: " .. drawCalls, x, 50)
  lg.print("BUG 1: .push('all') and .pop()", x, 100)
  lg.print("BUG 2: .setColor() w/ val over 255", x, 315)
end

function love.draw()
  love.graphics.clear(200, 200, 200)
  _helpDraw('Untouched Love2d', origLoveGraphics, 30)
  _helpDraw('autobatch.lua', love.graphics, 330)
end
```

Here's the output.

![image](https://user-images.githubusercontent.com/5661349/37198134-3211adb6-23cd-11e8-9539-aac9678624bc.png)

One other thing to note is that autobatch.lua takes **3** draw calls in order to draw everything. I suspect that it's possible to get this down to just 1 draw call.

**Comment by oniietzschan** [comment]
PS: I am personally going to be working on fixing these right away. I just thought I'd post the issue here right now just because I can.

**Comment by rxi** [comment]
I wanted to point out how excellent of an issue this is: a nicely commented example program, screenshot and a thorough description of what's wrong — the effort is appreciated!

If you don't get round to fixing the issue — at least concerning the push/pop problem — it is something I intend to sort out. In regard to the `setColor` problem, I had assumed values outside the `0..255` range did not have defined behaviour and that it wasn't something one should rely on, is this not the case? Has this always been how `setColor` worked or is it a recent change?

**Comment by oniietzschan** [comment]
Regarding push / pop, I've already spent some time looking at it and have come up with something that works in the isolation of the snippet I've provided, but is having some problems when I try to use it in my more complicated game project. I'm going to spend some more time tonight and see if I can't figure out where I've gone wrong.

Regarding setColor() > 255, I think you're quite right that it does not have defined behavior. I don't think autobatch is doing anything wrong here, it's just that SpriteBatch:setColor() behaves differently than love.graphics.setColor() with large values. So will not fix that one. It's too bad though, I've been using this property for a while now and thought it was highly convenient for certain effects.

**Comment by rxi** [comment]
I've pushed a commit for the push/pop issue — let me know if this fixes the issue in your game project! Thanks.

**Comment by oniietzschan** [comment]
It seems to work. Thanks for getting this done so promptly. Figures that the actual author of the library would be able to get a fix working before I could.

Still, I'll send you a PR in a second for a little opportunity for a cleanup I spotted.
